name: "Build image: FCOS Custom"

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Containerfile
          image: ziax-fcos-custom
          layers: false
          oci: true